services:
  - type: web
    name: backend-service
    env: node
    plan: free
    buildCommand: "cd packages/backend && npm install"
    startCommand: "cd packages/backend && npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000